#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : lua
Version  : 5.3.5
Release  : 56
URL      : http://www.lua.org/ftp/lua-5.3.5.tar.gz
Source0  : http://www.lua.org/ftp/lua-5.3.5.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: lua-bin = %{version}-%{release}
Requires: lua-lib = %{version}-%{release}
Requires: lua-man = %{version}-%{release}
BuildRequires : ncurses-dev
BuildRequires : readline-dev
Patch1: 0001-Build-fixes.patch
Patch2: CVE-2019-6706.patch
Patch3: fix_pc_for_5.3.5.patch
Patch4: 0001-Add-scimark-as-PGO-profiling-workload.patch
Patch5: 0001-Add-option-for-pgo-profiling-test-with-scimark.patch

%description
This is Lua 5.3.5, released on 26 Jun 2018.
For installation instructions, license details, and
further information about Lua, see doc/readme.html.

%package bin
Summary: bin components for the lua package.
Group: Binaries
Requires: lua-man = %{version}-%{release}

%description bin
bin components for the lua package.


%package dev
Summary: dev components for the lua package.
Group: Development
Requires: lua-lib = %{version}-%{release}
Requires: lua-bin = %{version}-%{release}
Provides: lua-devel = %{version}-%{release}

%description dev
dev components for the lua package.


%package lib
Summary: lib components for the lua package.
Group: Libraries

%description lib
lib components for the lua package.


%package man
Summary: man components for the lua package.
Group: Default

%description man
man components for the lua package.


%prep
%setup -q -n lua-5.3.5
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1550617366
export CFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "

export CFLAGS_GEN="$CFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo "
export LDFLAGS_GEN="$LDFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo "
export CFLAGS_USE="$CFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
export LDFLAGS_USE="$LDFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "

make  %{?_smp_mflags} linux MYCFLAGS="${CFLAGS_GEN} -fpic -DLUA_COMPAT_5_2 -DLUA_COMPAT_5_1" MYLDFLAGS="${LDFLAGS_GEN}" MYLIBS="-lncurses -lm"

make test_pgo

make clean
make  %{?_smp_mflags} linux MYCFLAGS="${CFLAGS_USE} -fpic -DLUA_COMPAT_5_2 -DLUA_COMPAT_5_1" MYLDFLAGS="${LDFLAGS_USE}" MYLIBS="-lncurses -lm"


%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make test

%install
export SOURCE_DATE_EPOCH=1550617366
rm -rf %{buildroot}
%make_install INSTALL_TOP=%{buildroot}/usr/

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/lua
/usr/bin/luac

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/include/*.hpp
/usr/lib64/*.a
/usr/lib64/liblua.so
/usr/lib64/pkgconfig/lua.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/liblua.so.5.3
/usr/lib64/liblua.so.5.3.5

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/lua.1
/usr/share/man/man1/luac.1
